./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/about.less ./NeoWeb/wwwroot/css/about.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/contributors.less ./NeoWeb/wwwroot/css/contributors.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/dev.less ./NeoWeb/wwwroot/css/dev.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/eco.less ./NeoWeb/wwwroot/css/eco.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/editor.less ./NeoWeb/wwwroot/css/editor.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/gov.less ./NeoWeb/wwwroot/css/gov.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/home.less ./NeoWeb/wwwroot/css/home.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/joinus.less ./NeoWeb/wwwroot/css/joinus.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/migration.less ./NeoWeb/wwwroot/css/migration.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/neogas.less ./NeoWeb/wwwroot/css/neogas.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/neogas.less ./NeoWeb/wwwroot/css/neogas.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/news.less ./NeoWeb/wwwroot/css/news.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/site.less ./NeoWeb/wwwroot/css/site.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/sitecn.less ./NeoWeb/wwwroot/css/sitecn.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/technology.less ./NeoWeb/wwwroot/css/technology.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/testnet.less ./NeoWeb/wwwroot/css/testnet.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/testnet-list.less ./NeoWeb/wwwroot/css/testnet-list.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/tour.less ./NeoWeb/wwwroot/css/tour.min.css
./node_modules/.bin/lessc -clean-css ./NeoWeb/wwwroot/css/wallet.less ./NeoWeb/wwwroot/css/wallet.min.css